/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as LayoutIndexRouteImport } from './routes/_layout/index'
import { Route as PerformanceSetlistIdRouteImport } from './routes/performance.$setlistId'
import { Route as LayoutSetlistsRouteImport } from './routes/_layout/setlists'
import { Route as SongArtistSlugSongSlugRouteImport } from './routes/song.$artistSlug.$songSlug'

const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const PerformanceSetlistIdRoute = PerformanceSetlistIdRouteImport.update({
  id: '/performance/$setlistId',
  path: '/performance/$setlistId',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutSetlistsRoute = LayoutSetlistsRouteImport.update({
  id: '/setlists',
  path: '/setlists',
  getParentRoute: () => LayoutRoute,
} as any)
const SongArtistSlugSongSlugRoute = SongArtistSlugSongSlugRouteImport.update({
  id: '/song/$artistSlug/$songSlug',
  path: '/song/$artistSlug/$songSlug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof LayoutIndexRoute
  '/setlists': typeof LayoutSetlistsRoute
  '/performance/$setlistId': typeof PerformanceSetlistIdRoute
  '/song/$artistSlug/$songSlug': typeof SongArtistSlugSongSlugRoute
}
export interface FileRoutesByTo {
  '/setlists': typeof LayoutSetlistsRoute
  '/performance/$setlistId': typeof PerformanceSetlistIdRoute
  '/': typeof LayoutIndexRoute
  '/song/$artistSlug/$songSlug': typeof SongArtistSlugSongSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/_layout/setlists': typeof LayoutSetlistsRoute
  '/performance/$setlistId': typeof PerformanceSetlistIdRoute
  '/_layout/': typeof LayoutIndexRoute
  '/song/$artistSlug/$songSlug': typeof SongArtistSlugSongSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/setlists'
    | '/performance/$setlistId'
    | '/song/$artistSlug/$songSlug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/setlists'
    | '/performance/$setlistId'
    | '/'
    | '/song/$artistSlug/$songSlug'
  id:
    | '__root__'
    | '/_layout'
    | '/_layout/setlists'
    | '/performance/$setlistId'
    | '/_layout/'
    | '/song/$artistSlug/$songSlug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
  PerformanceSetlistIdRoute: typeof PerformanceSetlistIdRoute
  SongArtistSlugSongSlugRoute: typeof SongArtistSlugSongSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/performance/$setlistId': {
      id: '/performance/$setlistId'
      path: '/performance/$setlistId'
      fullPath: '/performance/$setlistId'
      preLoaderRoute: typeof PerformanceSetlistIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/setlists': {
      id: '/_layout/setlists'
      path: '/setlists'
      fullPath: '/setlists'
      preLoaderRoute: typeof LayoutSetlistsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/song/$artistSlug/$songSlug': {
      id: '/song/$artistSlug/$songSlug'
      path: '/song/$artistSlug/$songSlug'
      fullPath: '/song/$artistSlug/$songSlug'
      preLoaderRoute: typeof SongArtistSlugSongSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface LayoutRouteChildren {
  LayoutSetlistsRoute: typeof LayoutSetlistsRoute
  LayoutIndexRoute: typeof LayoutIndexRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutSetlistsRoute: LayoutSetlistsRoute,
  LayoutIndexRoute: LayoutIndexRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
  PerformanceSetlistIdRoute: PerformanceSetlistIdRoute,
  SongArtistSlugSongSlugRoute: SongArtistSlugSongSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
